In [59]:
# import packages
import pandas as pd
import numpy as np

In [60]:
# load the dataset
from sklearn.model_selection import train_test_split

df = pd.read_csv('tainan_house.csv')
display(df.head())

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

# split the dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

,土地總面積平方公尺,總樓層數,建物型態,建物總面積平方公尺,房,廳,衛,有無管理,車位,電梯,...,鄉鎮市區_歸仁區,鄉鎮市區_永康區,鄉鎮市區_玉井區,鄉鎮市區_白河區,鄉鎮市區_西港區,鄉鎮市區_關廟區,鄉鎮市區_鹽水區,鄉鎮市區_麻豆區,鄉鎮市區_龍崎區,總價元(萬)
0,158.63,3.0,1.0,241.78,8.0,3.0,5.0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,4200.0
1,358.33,2.0,1.0,512.45,5.0,2.0,4.0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,8050.0
2,20.23,14.0,2.0,144.86,3.0,2.0,2.0,1,0.0,1,...,0,0,0,0,0,0,0,0,0,880.0
3,20.51,22.0,2.0,264.51,3.0,2.0,2.0,1,1.0,1,...,0,0,0,0,0,0,0,0,0,1860.0
4,11.46,14.0,2.0,139.66,1.0,0.0,1.0,1,0.0,1,...,0,0,0,0,0,0,0,0,0,330.0

In [61]:
# data normalization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train.values)  # learn distribution of traning data
X_train_nor = sc.transform(X_train.values) # 學完的data
X_test_nor = sc.transform(X_test.values)

In [62]:
# simple linear regression
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(X_train_nor, y_train.values)
r_squared = regr.score(X_train_nor, y_train.values)

print('截距項', regr.intercept_)
print('X係數', regr.coef_) # f(x)
print('R平方:',r_squared)

截距項 928.4861238677953
X係數 [ 4.77025940e+01 -1.43298752e+01 -1.16479776e+02  7.31798331e+02
 -2.77835717e+02  1.78506322e+01  2.05762766e+02 -2.50987560e+00
  7.51195833e+01 -1.00445678e+02  3.90279257e+13  4.41437553e+13
  1.46294796e+14  1.84974039e+14  9.41494181e+13  6.09965478e+13
  1.59163057e+14  1.03568772e+13  1.03568772e+13  1.53327303e+14
  1.22925951e+14  1.71709705e+13  5.50895565e+13  2.13019287e+14
  5.81207200e+13  1.79293386e+14  4.73357308e+13  3.06047042e+13
  2.31464524e+13  8.96961466e+12  2.97193872e+13  5.96870857e+13
  1.10298349e+14  1.28990105e+14  1.80585482e+14  2.37172724e+13
  4.00378293e+13  2.07055514e+13  1.00576292e+14  2.26577440e+14
  2.73800141e+13  3.54511820e+13  6.81167004e+13  5.92439281e+13
  6.45572645e+13  7.72766698e+13  5.17895113e+12]
R平方: 0.6073959300059079

In [63]:
total_value = [158, 3, 1, 241, 8, 3, 5, 0, 0, 0]
value3 = 2
# df.iloc[0,:].values

In [64]:
district = np.zeros(37)
district[value3] = 1           # 所在地區=1
print(district)
features = np.array(total_value)
real = np.concatenate((features, district))
real = np.array([real])


real_norm = sc.transform(real)
print(real_norm)
price = regr.predict(real_norm)
print(price)
# show_price(total_value, value3)'''

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[ 0.26788776 -0.86013004 -0.98976887  0.56488905  1.6803894   1.74775108
   0.85443856 -1.11742015 -0.67846023 -1.0863085  -0.06143765 -0.06956468
   4.11563623 -0.31974939 -0.15101992 -0.09655126 -0.26746898 -0.01624674
  -0.01624674 -0.25624923 -0.20053456 -0.0269484  -0.0870504  -0.38310515
  -0.09191956 -0.30782561 -0.07464924 -0.04810775 -0.03634802 -0.01406963
  -0.04670994 -0.09444079 -0.17848924 -0.21132642 -0.31051494 -0.03724687
  -0.06303996 -0.03250636 -0.1618641  -0.41717819 -0.04301892 -0.05577022
  -0.1080736  -0.09372712 -0.10230332 -0.12302553 -0.00812257]]
[1580.98612387]

In [65]:
# save the model and scaler
import pickle
pickle.dump(regr, open('model.pkl','wb'))
pickle.dump(sc, open('scaler.pkl','wb'))

In [66]:
# import the model and scalar
model = pickle.load(open('model.pkl','rb'))
scaler = pickle.load(open('scaler.pkl','rb'))

In [67]:
# next time you shoud use the data in this format
# np.array([x, x, x, ])